[
  {
    id: 1,
    name: "John",
    date: "2024-05-11",
    nftId: "0x334400",
    nftUrl: "https://cdn.pixabay.com/photo/2023/07/14/01/35/ai-generated-8126073_1280.jpg",
    topic: "Intro to Blockchain Technology",
    desc: "This session provides an overview of blockchain technology, including its history, fundamental concepts, and potential applications.",
    attendence: 4,
  },
  {
    id: 2,
    name: "Alice",
    date: "2024-05-18",
    nftId: "0x445511",
    nftUrl: "https://cdn.pixabay.com/photo/2022/09/11/04/28/monkey-7446118_1280.png",
    topic: "Smart Contracts and Ethereum",
    desc: "In this session, we explore smart contracts on the Ethereum platform, discussing their functionality, development, and real-world use cases.",
    attendence: 7,
  },
  {
    id: 3,
    name: "Bob",
    date: "2024-05-25",
    nftId: "0x556622",
    nftUrl: "https://cdn.pixabay.com/photo/2022/02/14/02/52/monkey-7012380_1280.png",
    topic: "Decentralized Applications (dApps)",
    desc: "This session covers the development and deployment of decentralized applications (dApps), focusing on their architecture and impact on various industries.",
    attendence: 5,
  },
  {
    id: 4,
    name: "Charlie",
    date: "2024-06-01",
    nftId: "0x667733",
    nftUrl: "https://cdn.pixabay.com/photo/2022/11/02/16/04/portrait-7565264_1280.jpg",
    topic: "Blockchain and Cryptocurrencies",
    desc: "An in-depth look at the relationship between blockchain technology and cryptocurrencies, including mining, transaction processing, and market trends.",
    attendence: 6,
  },
  {
    id: 5,
    name: "Diana",
    date: "2024-06-08",
    nftId: "0x778844",
    nftUrl: "https://cdn.pixabay.com/photo/2023/03/30/16/00/ai-generated-7888106_1280.jpg",
    topic: "Blockchain Security and Privacy",
    desc: "This session delves into the security and privacy aspects of blockchain technology, covering common vulnerabilities, best practices, and emerging solutions.",
    attendence: 8,
  },
  {
    id: 6,
    name: "Eve",
    date: "2024-06-15",
    nftId: "0x889955",
    nftUrl: "https://cdn.pixabay.com/photo/2022/11/02/16/04/digital-art-7565263_1280.jpg",
    topic: "Future Trends in Blockchain",
    desc: "Exploring the future trends in blockchain technology, this session discusses potential advancements, new applications, and the evolving landscape of decentralized systems.",
    attendence: 9,
  },
];
